### ISSUE TITLE
Icons not displayed in IE/Older versions of iOS Safari

### ISSUE THREAD

**Issue by purtuga** [webkul/vivid#3]
> First: Great project. I been looking to use SVG allot more for icons and this is great for me - so: THANK YOU. :+1: 

Just FYI - I'm not sure if you are already aware of this. Your showcase website does not actually render the icons to the page under IE (11) or older versions of iOS safari. In IE, I can see the `<i/>` tags in the page, which implies that your code did not replace them with the corresponding SVG image. 

For the record: they DO display fine in IE11 when the SVG is inserted. 

My guess is your `inject.js` file - it assumes that `querySelectorAll()` returns an Array, because right after you attempt to use the `forEach()` method: https://github.com/webkul/vivid/blob/65cef2ff7a3c36ba01de6b6189a3f0ca3043eac7/src/inject.js#L8

**Comment by CreativeGP** [comment]
Should we use this instead?
```javascript
Array.prototype.forEach.call(vividNode, funtion (item, key) {
});
```

https://stackoverflow.com/a/22416614

**Comment by purtuga** [comment]
Yes, that will work :)

And: I'm sorry for just opening the issue... I should have just submitted a pull request and fix it. I was not actually using this library - only "looking around" after finding it via Twitter mention.

**Comment by nitishkmrk** [comment]
We are not targeting IE either way :) Thanks for showing interest.
