### ISSUE TITLE
Issues displaying multiple of the same icon?

### ISSUE THREAD

**Issue by LDShadowLord** [webkul/vivid#5]
I have two of the "arrow-left" icons serving as Go Back links. I have one at the top and one at the bottom of the page.
Only the bottom icon is displaying, the top icon is vanishing with the entire <i> tag disappearing in the HTML code. It appears that no matter how many of the same icon I put on the page, only the last rendered icon actually displays.
I am loading the code from your CDN, and each icon is identical in size and colour. No errors are being logged to console.

**Comment by ATechAdventurer** [comment]
I just noticed that as well. Here is a codepen demonstrating the issue: [https://codepen.io/XXTheEnd32XX/pen/QxpRXr](https://codepen.io/XXTheEnd32XX/pen/QxpRXr)

**Comment by nitishkmrk** [comment]
This issue has been resolved in v1.0.2
